# Generated by Django 2.2.1 on 2019-05-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=450)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_percentage', models.PositiveIntegerField(null=True)),
                ('exp', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_missions', to='missions.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='missions.Mission')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='character.Skill')),
            ],
        ),
    ]
