# Generated by Django 2.2.1 on 2019-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0002_auto_20190605_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='habit',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='run_at',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='week_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('habit', 'date')},
        ),
    ]
